name       : haskell-aeson-compat
version    : 0.3.6
release    : 1
source     :
    - http://hackage.haskell.org/package/aeson-compat-0.3.6/aeson-compat-0.3.6.tar.gz : 7aa365d9f44f708f25c939489528836aa10b411e0a3e630c8c2888670874d142
license    : BSD-3-Clause
component  : programming.haskell
summary    : Compatibility layer for aeson
description: |
    Compatibility layer for aeson
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-nats
    - haskell-semigroups
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
