name       : haskell-aeson-compat
version    : 0.3.7.1
release    : 2
source     :
    - http://hackage.haskell.org/package/aeson-compat-0.3.7.1/aeson-compat-0.3.7.1.tar.gz : 59740dc1e37b08e60abb47f38b87de5b9805611a1b468cd18294d5982a1dcacb
license    : BSD-3-Clause
component  : programming.haskell
summary    : Compatibility layer for aeson
description: |
    Compatibility layer for aeson
builddeps  :
    - haskell-aeson
    - haskell-attoparsec-iso8601
    - haskell-base-compat
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-semigroups
setup      : |
    sed -i "s|<0.9|<0.11|g" aeson-compat.cabal
    sed -i "s|<0.10|<0.11|g" aeson-compat.cabal
    sed -i "s|<1.3|<1.4|g" aeson-compat.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
