name       : haskell-aeson-compat
version    : 0.3.9
release    : 3
source     :
    - https://hackage.haskell.org/package/aeson-compat-0.3.9/aeson-compat-0.3.9.tar.gz : e043941ba761c13a3854fc087521b864b56b2df874154e42aedb67b2a77f23c8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Compatibility layer for aeson
description: |
    Compatibility layer for aeson
builddeps  :
    - haskell-aeson-devel
    - haskell-attoparsec-iso8601-devel
    - haskell-base-orphans-devel
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-time-locale-compat-devel
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-attoparsec-iso8601-devel
        - haskell-base-orphans-devel
        - haskell-exceptions-devel
        - haskell-time-locale-compat-devel
networking : yes
setup      : |
    sed -i "s|<1.5|<1.6|g" aeson-compat.cabal   # aeson
    sed -i "s|<0.11|<0.12|g" aeson-compat.cabal # base-compat
    sed -i "s|<1.3|<1.4|g" aeson-compat.cabal   # hashable
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
